#!/usr/bin/env node

const path = require("path");
const { execSync } = require("child_process");

const util = require("node:util");
const exec = util.promisify(require("node:child_process").exec);

const projectRoot = path.join(__dirname, "..");

console.log(projectRoot);